# Generated by Django 4.2.4 on 2023-08-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment'),
        ('main_app', '0003_photo'),
    ]

    operations = [
    ]
